local harpoon = require("harpoon")

-- harpoon:setup()

vim.keymap.set("n", "<leader>h", "", { desc = "Harpoon" })
vim.keymap.set("n", "<leader>ha", function()
  harpoon:list():add()
end, { desc = "Harpoon add to list" })
vim.keymap.set("n", "<leader>hd", function()
  harpoon:list():remove()
end, { desc = "Harpoon remove current buffer from the list" })
vim.keymap.set("n", "<leader>hc", function()
  harpoon:list():clear()
end, { desc = "Harpoon clear list" })
vim.keymap.set("n", "<leader>hu", function()
  harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Harpoon toggle list UI" })

--
vim.keymap.set("n", "<leader>h1", function()
  harpoon:list():select(1)
end, { desc = "Harpoon select 1st item" })
vim.keymap.set("n", "<leader>h2", function()
  harpoon:list():select(2)
end, { desc = "Harpoon select 2nd item" })
vim.keymap.set("n", "<leader>h3", function()
  harpoon:list():select(3)
end, { desc = "Harpoon select 3rd item" })
vim.keymap.set("n", "<leader>h4", function()
  harpoon:list():select(4)
end, { desc = "Harpoon select 4th item" })
--
-- Toggle previous & next buffers stored within Harpoon list
vim.keymap.set("n", "<leader>hn", function()
  harpoon:list():prev()
end, { desc = "Harpoon next item" })
vim.keymap.set("n", "<leader>hp", function()
  harpoon:list():next()
end, { desc = "Harpoon previous item" })
