# since after chsh the shell may have to be restarted,
# this script for now only servers as a documentation
ubuntu:
	sudo apt install zsh
	chsh
	source ubuntu.setup.sh
	source setup.sh
	source ~/.zshrc

